@host = http://localhost:8080

###
GET {{host}} HTTP/1.1

###
GET {{host}}/people HTTP/1.1

###
POST {{host}}/people HTTP/1.1
content-type: application/json

{
    "firstName" : "Dirck",  
    "lastName" : "Hecking" 
}

###
POST {{host}}/people HTTP/1.1
content-type: application/json

{
    "firstName" : "Shar",  
    "lastName" : "Kondzela" 
}

###
DELETE {{host}}/people/2 HTTP/1.1

###
GET {{host}}/people?page=0&size=100 HTTP/1.1

###
GET {{host}}/profile HTTP/1.1

###
GET {{host}}/profile/people HTTP/1.1


