@lcl = http://localhost:8080

@gcp = https://mysql-dot-spring-380702.uk.r.appspot.com

@host = {{gcp}}

###
GET {{host}}/demo/all HTTP/1.1

###
POST {{host}}/demo/add?name=candy&email=candy@gmail.com HTTP/1.1
