@lcl = http://localhost:8080

@gcp = https://mysql-dot-justadirck.uc.r.appspot.com

@host = {{gcp}}

###
GET {{host}} HTTP/1.1

###
GET {{host}}/people HTTP/1.1

###
POST {{host}}/people HTTP/1.1
content-type: application/json

{
    "name" : "dirck",  
    "email" : "dirck@gmail.com" 
}

###
PATCH {{host}}/people/1 HTTP/1.1
content-type: application/json

{ 
    "email" : "carly@sankaku.com" 
}

###
PUT {{host}}/people/5 HTTP/1.1
content-type: application/json

{
    "first" : "yoshi",  
    "last" : "five",  
    "email" : "yoshi@gmail.com" 
}


###
DELETE {{host}}/people/152 HTTP/1.1
