@lcl = http://localhost:8080

@gcp = https://mysql-dot-justadirck.uc.r.appspot.com

@host = {{gcp}}

###
GET {{host}}/demo/all HTTP/1.1

###
POST {{host}}/demo/add?name=mysql&email=mysql@gmail.com HTTP/1.1
