@lcl = http://localhost:8080

@gcp = https://postgres-dot-justadirck.uc.r.appspot.com

@host = {{lcl}}

###
GET {{host}}/all HTTP/1.1

###
POST {{host}}/add?name=postgres&email=postgres@gmail.com HTTP/1.1
