@lcl = http://localhost:8080

@gcp = https://postgres-dot-justadirck.uc.r.appspot.com

@host = {{gcp}}

###
GET {{host}}/demo/all HTTP/1.1

###
POST {{host}}/demo/add?name=postgres&email=postgres@gmail.com HTTP/1.1
